In [2]:
import numpy as np

arr = np.array([5, 8, 3, 10])
print(arr)
print(type(arr))

[ 5  8  3 10]
<class 'numpy.ndarray'>


In [10]:
import numpy as np

arr_1 = np.array([5, 8, 3, 10])
arr_2 = np.array([6, 2, 8, 11])

result_addition = arr_1 + arr_2
print(result_addition)


[11 10 11 21]


In [ ]:
result_subtraction = arr_1 - arr_2
print(result_subtraction)

[-1  6 -5 -1]


In [8]:
result_multiple = arr_1 * arr_2
print(result_multiple)

[ 30  16  24 110]


In [11]:
result_devision = arr_1 / arr_2
print(result_devision)

[0.83333333 4.         0.375      0.90909091]


In [12]:
arr_1 = np.array([16, 9, 36, 100])
print(np.sqrt(arr_1))

[ 4.  3.  6. 10.]


In [13]:
print(np.sum(arr_1))

161


In [17]:
print(np.max(arr_1))


100


In [16]:
print(np.min(arr_1))

9


In [ ]:
arr_1 = np.array([[9, 10, 5] , [8, 12, 20]])
print(arr_1)
print(arr_1.size)
print(arr_1.shape)
print(arr_1.ndim)

[[ 9 10  5]
 [ 8 12 20]]
6
(2, 3)
2


In [ ]:
arr_1 = np.array([[[9, 10, 5], [8, 12, 20]], [[1, 2, 3], [4, 5, 6]]])
print(arr_1.size)
print(arr_1.shape)
print(arr_1.ndim)

12
3
(2, 2, 3)


In [33]:
array = np.array([1, 2, True ])
print(array.dtype)

int64


In [36]:
arr_2 = np.array([[5, 3, 8], [4, 9, 10]])
print(arr_2[1, 2]) 
print(arr_2[-2, -2])

10
3


In [37]:
arr = np.array([30, 10, 40, 50, 20])
condition = arr > 25
print(condition)

[ True False  True  True False]


In [38]:
print(arr[condition]) 

[30 40 50]


In [39]:
print(arr[arr > 25])  

[30 40 50]


In [ ]:
arr = np.array([30, 10, 40, 50, 20])
print(arr[(arr > 25) & (arr < 45)])

[30 40]


In [54]:
body_tempreture = np.array([
    [31, 30, 28], 
    [29, 29, 32],
    [26, 24, 27], 
    [31, 34, 35], 
    [28, 31, 30]
    ])

daily_average = np.mean(body_tempreture)
# daily_average = np.sum(body_tempreture)/(body_tempreture.size)
print(daily_average)

print(body_tempreture[body_tempreture > daily_average])


29.666666666666668
[31 30 32 31 34 35 31 30]


In [ ]:
print(np.zeros((2, 3))) 
print(np.zeros(5))


[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [60]:
print(np.ones((2, 3)))                  
print(np.ones(5))

[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [62]:
print(np.full((2, 3), 7))
print(np.full(5, 7))

[[7 7 7]
 [7 7 7]]
[7 7 7 7 7]


In [68]:
print(np.full((2, 3), (1,2,3)))

[[1 2 3]
 [1 2 3]]


In [69]:
print(np.empty((2, 3)))

[[4.9e-324 9.9e-324 1.5e-323]
 [4.9e-324 9.9e-324 1.5e-323]]


In [78]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],}

df = pd.DataFrame(data)
print(df)


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40


In [ ]:
print(df.loc[0,'Name'])
print(df.iloc[2, 1])  # Accessing by index

KeyError: 0

In [88]:
print(df.loc[2])  
print(df.iloc[2]) 

Name    Charlie
Age          35
Name: 2, dtype: object
Name    Charlie
Age          35
Name: 2, dtype: object


In [ ]:
df = pd.DataFrame(data, index=['student_1', 'student_2', 'student_3', 'student_4'])
print(df)


              Name  Age
student_1    Alice   25
student_2      Bob   30
student_3  Charlie   35
student_4    David   40
30
Name    Charlie
Age          35
Name: student_3, dtype: object


In [124]:
print(df.loc['student_3'])
print(df.iloc[1]) 

Name    Charlie
Age          35
Name: student_3, dtype: object
Name    Bob
Age      30
Name: student_2, dtype: object


In [101]:
print(df.loc[['student_1', 'student_3']])

              Name  Age
student_1    Alice   25
student_3  Charlie   35


In [108]:
age_column = df[['Age']]
print(age_column)

           Age
student_1   25
student_2   30
student_3   35
student_4   40


In [113]:
print(df.columns)  # Displaying column names
print(list(df.columns))  

Index(['Name', 'Age'], dtype='object')
['Name', 'Age']


In [ ]:
print(df.index)  # Displaying index names
print(list(df.index)) 

Index(['student_1', 'student_2', 'student_3', 'student_4'], dtype='object')
['student_1', 'student_2', 'student_3', 'student_4']


In [123]:
print(df.size)
print(df.shape)
print(len(df))  # Number of rows

8
(4, 2)
4
